import "./globals.css";
import type { Metadata } from "next";
import { QueryClient, QueryClientProvider } from "react-query";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = new QueryClient();
  return (
    <html lang="en">
      <body className="flex flex-col min-h-[100vh] justify-between bg-LightBg dark:bg-DarkBg">
        <QueryClientProvider client={client}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
