import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import QueryProvider from "@/components/QueryProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <QueryProvider>
      <html lang="en">
        <body className="flex flex-col min-h-[100vh] justify-between bg-LightBg dark:bg-DarkBg">
          <Navbar />
          {children}
        </body>
      </html>
    </QueryProvider>
  );
}
